### ISSUE TITLE
Cloud requests not working

### ISSUE THREAD

**Issue by banddans** [TheCommCraft/scratchcommunication#4]
So... I realized that I hadn't enabled some certificate stuff in my python, that solved the old problem. Now I'm able to set cloud variables but cloud requsts aren't working. Each time I send a request the project doesn't respond. Here's my code:

```
import scratchcommunication

PROJECT_ID = "1048255167"

print("Creating session...")
session = scratchcommunication.Session("banddans", session_id="")

print("Creating socket...")

key_file = open("key.txt", "r")
security = scratchcommunication.security.Security.from_string(key_file.read())
key_file.close()

cloud_socket = session.create_turbowarp_cloud_socket(
    contact_info="banddans",
    project_id=PROJECT_ID,
    security=security,
)

print("Creating requests...")
cloud_requests = scratchcommunication.RequestHandler(
    cloud_socket=cloud_socket,
)


@cloud_requests.request
def ping():
    print("Got request!")
    return "secret pong"


print("Running!")

cloud_requests.start()```

Project: https://turbowarp.org/1048256250

And gen_key.py:

```
import scratchcommunication

security = scratchcommunication.security.Security.generate()

file = open("key.txt", "w")
file.write(security.to_string())
file.close()

print("Key generated succesfully!")

```

**Comment by TheCommCraft** [comment]
1. The project id doesn't match the link you gave me
2. The link you gave me doesn't have a cloud requests module in it

**Comment by TheCommCraft** [comment]
Make sure you are not looking inside the project on turbowarp and that the key exchange data on the frontend is correct

**Comment by banddans** [comment]
> 1. The project id doesn't match the link you gave me 2. The link you gave me doesn't have a cloud requests module in it

Ah sorry, I meant https://scratch.mit.edu/projects/1048255167/

**Comment by banddans** [comment]
Hmmm... not looking inside and i think i did the key correct

**Comment by TheCommCraft** [comment]
Try adding a script to your backend that prints something every time there
is a cloud update like in the example script

banddans ***@***.***> schrieb am Fr., 19. Juli 2024, 14:21:

**Comment by TheCommCraft** [comment]
Closing this for now. If you have more questions, reopen this topic or create a new one.
