### ISSUE TITLE
Add a purpose argument for the 'TwCloudConnection' argument

### ISSUE THREAD

**Issue by zaid4412100** [TheCommCraft/scratchcommunication#5]
Add the purpose argument like the one in scratchattach for the Turbowarp function.

It will allow anyone managing the cloud server understand more.

**Comment by TheCommCraft** [comment]
I have `contact` in which you can just include the purpose

**Comment by zaid4412100** [comment]
Oh ok. I checked scratchattach's source code and it seems it just adds the purpose and contact together.

**Comment by TheCommCraft** [comment]
Yeah I know, that's why I just made it one argument

Zaid ***@***.***> schrieb am Mi., 31. Juli 2024, 18:08:
