### ISSUE TITLE
create SECURITY.md

### ISSUE THREAD

**Issue by LeanderKafemann** [TheCommCraft/scratchcommunication#6]
Could you please create a SECURITY.md file here so we know which versions are currently supported etc.?

**Comment by TheCommCraft** [comment]
ok

Leander Kafemann ***@***.***> schrieb am Fr., 9. Aug. 2024,
12:36:

**Comment by LeanderKafemann** [comment]
thx

**Comment by TheCommCraft** [comment]
Can this be closed?

**Comment by LeanderKafemann** [comment]
Yes, but could you add information about previous releases?

**Comment by TheCommCraft** [comment]
I will have to look at the releases

Leander Kafemann ***@***.***> schrieb am Fr., 9. Aug. 2024,
18:45:
